"""Русские тексты. Ключи должны точно совпадать с en.py."""
from __future__ import annotations

TEXTS: dict[str, str] = {
    # --- Общее ---
    "btn_back": "◀️ Назад",
    "btn_cancel": "Отмена",
    "cancelled": "Отменено.",
    "btn_confirm": "Подтвердить",
    "btn_yes": "Да",
    "btn_no": "Нет",

    "error_generic": "Что-то пошло не так. Попробуйте ещё раз.",
    "error_permission_denied": "Недостаточно прав.",
    "error_not_found": "Не найдено.",
    "error_concurrency": "Кто-то уже делает это. Попробуйте через секунду.",
    "error_insufficient_funds": "Не хватает средств.",
    "error_banned": "Доступ ограничен.",
    "error_flood": "Слишком быстро. Подождите немного.",

    # --- Первый запуск / документация ---
    "choose_language": "Выберите язык:",
    "docs_intro": "Прежде чем начать — короткие правила игры.",
    "docs_agree_btn": "✅ Принимаю",
    "docs_declined": "Без согласия с правилами игра недоступна.",
    "agreement_accepted": "Готово. Добро пожаловать.",
    "main_menu_title": "Главное меню.",
    "start_private_required": "Для регистрации напишите боту в личные сообщения.",
    "start_group_greeting": "Бот готов к игре. Управление — командами или через ЛС.",
    "help_text": "Игра: открывайте контейнеры на аукционе, собирайте машины, прокачивайте гараж. Подробности — в Настройках → Документация.",

    # --- Главное меню ---
    "menu_play": "🎮 Играть",
    "menu_profile": "👤 Профиль",
    "menu_garage": "🚗 Гараж",
    "menu_battle_pass": "🎫 БП",
    "menu_skills": "⬆️ Навыки",
    "menu_leaderboard": "🏆 Лидерборд",
    "menu_shop": "🛒 Магазин",
    "menu_referrals": "👥 Рефералы",
    "menu_settings": "⚙️ Настройки",

    # --- Контейнеры / аукцион ---
    "container_card": (
        "📦 Контейнер:\n"
        "🌍 Страна: {country}\n"
        "💰 Первоначальная ставка: {initial_bid}\n"
        "🔥 Последняя ставка: {last_bid}\n"
        "⏱ До окончания: {seconds_left} сек.\n"
        "👤 Лидер: {leader}"
    ),
    "container_no_leader": "—",
    "container_no_bids_closed": "Ставок не было. Контейнер закрыт.",
    "container_empty": "В этом контейнере нет доступных машин.",
    "container_none_enabled": "Сейчас нет включённых контейнеров.",
    "chance_title": "🎲 Текущие шансы редкости:",
    "chance_line": "{label}: {percent}%",
    "bet_too_low": "Ставка ниже минимальной. Нужно не меньше {min_amount}.",
    "bet_accepted": "Ставка принята: {amount}.",
    "auction_won": "🏆 Контейнер выигран за {amount}.",
    "room_full_new_opened": "Комната заполнена. Открыта новая — №{room_number}.",
    "room_status": "Комната №{room_number} · {count}/{capacity} игроков.",
    "kicked_inactivity": "Вы пропустили несколько контейнеров подряд и выведены из комнаты.",
    "leave_room_btn": "🚪 Выйти из комнаты",
    "group_auction_disabled": "Аукцион в этой группе сейчас недоступен.",
    "left_room": "Вы вышли из комнаты.",
    "stop_scheduled": "Аукцион остановится после текущего контейнера.",

    # --- Машина после открытия ---
    "car_card": (
        "{rarity_label} {name}\n"
        "🆔 {car_id}\n"
        "🌍 {country}\n"
        "🏁 Макс. скорость: {max_speed} км/ч\n"
        "⚡ 0-100: {accel} сек\n"
        "💪 Мощность: {power} л.с.\n"
        "🎮 Управляемость: {handling}\n"
        "🔧 Надёжность: {reliability}\n"
        "💵 Стоимость: {price}"
    ),
    "rarity_common": "⚪ Обычная",
    "rarity_rare": "🔵 Редкая",
    "rarity_epic": "🟣 Эпическая",
    "rarity_mythic": "🟡 Мифическая",
    "car_not_found": "Машина с таким ID не найдена.",
    "car_id_required": "Укажите ID машины, например: /car 12",
    "sell_invalid_args": "Формат: /sellcar ID  или  /sell ID ПОКУПАТЕЛЬ ЦЕНА",
    "transfer_invalid_args": "Формат: /transfer ПОЛУЧАТЕЛЬ СУММА",
    "sell_btn": "💰 Продать",
    "sell_success": "Продано за {amount}.",
    "sell_prompt_expired": "Время на решение вышло.",

    # --- Гараж ---
    "garage_title": "🚗 Гараж: {count}/{capacity}",
    "garage_empty": "Гараж пуст.",
    "garage_full_auto_sold": "Гараж был полон — новая машина автоматически продана за {amount}.",
    "garage_upgrade_btn": "➕ Увеличить гараж",
    "garage_upgrade_success": "Гараж увеличен до {capacity}.",
    "garage_upgrade_max": "Достигнут максимум вместимости.",

    # --- Профиль ---
    "profile_title": "👤 Профиль",
    "profile_balance": "💰 Баланс: {balance}",
    "profile_vip": "👑 VIP",
    "profile_cars_count": "🚗 Машин: {count}",
    "daily_bonus_btn": "🎁 Ежедневный бонус",
    "daily_bonus_claimed": "Начислено: {amount}.",
    "daily_bonus_already": "Бонус уже получен сегодня.",

    "stats_title": "📊 Статистика",
    "stats_containers_opened": "Открыто контейнеров: {value}",
    "stats_bids_made": "Сделано ставок: {value}",
    "stats_wins": "Побед: {value}",
    "stats_cars_obtained": "Получено машин: {value}",
    "stats_cars_sold": "Продано машин: {value}",
    "stats_earned_total": "Заработано: {value}",
    "stats_spent_total": "Потрачено: {value}",
    "stats_container_profit": "Профит от контейнеров: {value}",
    "stats_referrals_count": "Приглашено рефералов: {value}",

    # --- VIP ---
    "vip_username_prefix": "👑 ",
    "vip_purchase_success": "VIP активирован — навсегда.",
    "vip_already_owned": "У вас уже есть VIP.",
    "vip_offer": "👑 VIP — навсегда.\nЦена: {price}\n\nПреимущества: сниженные комиссии, +10 мест в гараже.",
    "vip_buy_btn": "👑 Купить VIP",

    # --- Лидерборд ---
    "top_title_rich": "🏆 Топ богатых",
    "top_title_racers": "🏆 Топ гонщиков",
    "top_title_profit": "🏆 Топ по профиту от контейнеров",
    "top_title_group": "🏆 Топ группы",
    "leaderboard_empty": "Пока никого нет в рейтинге.",

    # --- Рефералы ---
    "referrals_title": "👥 Рефералы",
    "referrals_invited_count": "Приглашено: {count}",
    "referrals_progress": "До эпической машины: {progress}/{threshold}",
    "referral_bonus_received": "Реферальный бонус: +{amount}.",
    "referral_already_registered": "Этот игрок уже зарегистрирован.",

    # --- Battle Pass ---
    "bp_title": "🎫 Battle Pass",
    "bp_not_purchased": "Battle Pass ещё не куплен.",
    "bp_already_purchased": "Battle Pass уже куплен.",
    "bp_offer": "🎫 Battle Pass\nЦена: {price}\nУровней: {levels}",
    "bp_offer_buy_btn": "🎫 Купить Battle Pass",
    "bp_purchase_success": "Battle Pass активирован.",
    "bp_level_progress": "Уровень: {level}/{max_level}",
    "bp_level_up": "🎫 Новый уровень Battle Pass: {level}.",

    # --- Магазин ---
    "shop_title": "🛒 Магазин",
    "shop_empty": "Магазин пуст.",
    "shop_purchase_success": "Покупка оформлена.",
    "shop_purchase_unavailable": "Лот сейчас недоступен.",

    # --- Промокоды ---
    "promo_prompt": "Введите промокод:",
    "promo_success": "Промокод активирован.",
    "promo_invalid": "Промокод не найден или недействителен.",
    "promo_already_used": "Вы уже использовали этот промокод.",
    "promo_expired": "Срок действия промокода истёк.",
    "promo_limit_reached": "Лимит активаций исчерпан.",

    # --- Настройки ---
    "settings_title": "⚙️ Настройки",
    "settings_language": "🌐 Язык",
    "settings_help": "❓ Помощь",
    "settings_documentation": "📖 Документация",
    "settings_promo": "🎟 Промокод",
    "settings_group": "👥 Группа",
    "settings_support": "🆘 Поддержка",
    "settings_statistics": "📊 Статистика",
    "support_prompt": "Опишите проблему (минимум 5 слов):",
    "support_too_short": "Сообщение слишком короткое — опишите подробнее.",
    "support_sent": "Обращение отправлено.",

    # --- Экономика ---
    "transfer_success": "Переведено {amount} игроку {target}.",
    "sell_state_success": "Продано государству за {amount}.",
    "sell_player_offer_sent": "Предложение отправлено.",
    "sell_player_offer_received": "💰 Вам предлагают купить {car_name} за {price}.",
    "sell_player_buy_btn": "💰 Купить",
    "sell_player_decline_btn": "❌ Отклонить",
    "sell_player_accepted": "Сделка завершена.",
    "sell_player_declined": "Предложение отклонено.",

    # --- Админ ---
    "admin_permission_denied": "Недостаточно прав администратора.",
    "admin_action_done": "Готово.",
    "admin_menu_title": "🛠 Админ-панель",
    "admin_section_coming_soon": "Раздел в разработке.",
    "admin_section_users": "👤 Пользователи",
    "admin_section_cars": "🚗 Машины",
    "admin_section_containers": "📦 Контейнеры",
    "admin_section_garage": "🏠 Гараж",
    "admin_section_shop": "🛒 Магазин",
    "admin_section_battle_pass": "🎫 Battle Pass",
    "admin_section_vip": "👑 VIP",
    "admin_section_promo": "🎟 Промокоды",
    "admin_section_groups": "👥 Группы",
    "admin_section_broadcasts": "📣 Рассылки",
    "admin_section_statistics": "📊 Статистика",
    "admin_section_documentation": "📖 Документация",
    "admin_section_database": "🗄 База данных",
    "admin_section_backups": "💾 Резервные копии",
    "admin_section_admins": "🛡 Администраторы",
    "admin_users_search_prompt": "Введите Telegram ID или username игрока:",
    "admin_users_not_found": "Игрок не найден.",
    "admin_users_multiple_matches": "Найдено несколько игроков — выберите:",
    "admin_user_banned_label": "🚫 Заблокирован",
    "admin_action_balance": "💰 Изменить баланс",
    "admin_action_ban": "🚫 Заблокировать",
    "admin_action_unban": "✅ Разблокировать",
    "admin_action_vip_grant": "👑 Выдать VIP",
    "admin_action_vip_revoke": "👑 Забрать VIP",
    "admin_balance_prompt": "Введите сумму изменения (например: 1000 или -500):",
    "admin_balance_invalid": "Нужно целое число, например: 1000 или -500.",
    "admin_format_invalid": "Неверный формат. Проверьте ввод и попробуйте ещё раз.",
    "admin_cars_title": "🚗 Машины",
    "admin_cars_empty": "Машин пока нет.",
    "admin_car_create_btn": "➕ Создать машину",
    "admin_car_create_prompt": "Пришлите одним сообщением (можно с фото — тогда в подписи):\nназвание | страна | редкость | макс.скорость | 0-100 | мощность | управляемость | надёжность | стоимость\n\nРедкость: common / rare / epic / mythic.\nПример: Toyota Supra | Япония | rare | 285 | 4.6 | 340 | 82 | 75 | 90000",
    "admin_car_format_invalid": "Не удалось разобрать данные машины. Нужно 9 полей через « | », редкость — common/rare/epic/mythic, числа — целые (0-100 можно с точкой).",
    "admin_car_created": "Машина создана: ID {car_id}.",
    "admin_car_updated": "Машина обновлена.",
    "admin_car_edit_btn": "✏️ Изменить",
    "admin_car_edit_prompt": "Пришлите строки вида поле=значение, например:\nprice=150000\nrarity=epic\n\nПоля: name, country, rarity, max_speed, accel, power, handling, reliability, price.",
    "admin_car_hide_btn": "🗑 Скрыть",
    "admin_car_restore_btn": "♻️ Вернуть",
    "admin_car_inactive_label": "🚫 Скрыта",
    "admin_containers_title": "📦 Контейнеры",
    "admin_containers_empty": "Контейнеров пока нет.",
    "admin_container_create_btn": "➕ Создать контейнер",
    "admin_container_create_prompt": "Пришлите одним сообщением (можно с фото — тогда в подписи):\nназвание | страна | цена\n\nЦена = первоначальная ставка. Пример: Японский | Япония | 10000",
    "admin_container_created": "Контейнер создан: ID {container_id}.",
    "admin_container_updated": "Контейнер обновлён.",
    "admin_container_edit_btn": "✏️ Изменить",
    "admin_container_edit_prompt": "Пришлите строки вида поле=значение, например:\nprice=12000\n\nПоля: name, country, price.",
    "admin_container_add_car_btn": "➕ Добавить машину",
    "admin_container_add_car_prompt": "Введите: ID_машины [вес]. Вес по умолчанию 1; повторный ввод обновляет вес.",
    "admin_container_remove_car_btn": "➖ Убрать машину",
    "admin_container_remove_car_prompt": "Введите ID машины, которую убрать из контейнера:",
    "admin_container_disable_btn": "🔴 Выключить",
    "admin_container_enable_btn": "🟢 Включить",
    "admin_container_disabled_label": "🔴 Выключен",
    "admin_container_price_line": "💰 Первоначальная ставка: {price}",
    "admin_container_no_cars": "Состав пуст — контейнер не сможет выдать машину.",
    "admin_container_cars_line": "🆔 {car_id} · {name} · вес {weight}",
    "admin_garage_title": "🏠 Гараж — тарифы расширения",
    "admin_garage_no_tiers": "Тарифов нет — игроки не смогут расширять гараж.",
    "admin_garage_tier_line": "{capacity} мест — {price}",
    "admin_garage_tier_add_btn": "➕ Тариф",
    "admin_garage_tier_add_prompt": "Введите: вместимость цена (например: 20 25000). Существующий тариф обновится.",
    "admin_garage_tier_del_btn": "➖ Удалить тариф",
    "admin_garage_tier_del_prompt": "Введите вместимость тарифа, который удалить:",
    "admin_garage_limits_btn": "⚙️ Лимиты",
    "admin_garage_limits_prompt": "Введите: максимум_без_VIP бонус_мест_VIP (например: 50 10):",
    "admin_garage_limits_line": "Максимум без VIP: {max} · бонус мест VIP: {bonus}",
    "admin_shop_price_line": "💰 Цена: {price}",
    "admin_shop_disabled_label": "🔴 Недоступен",
    "admin_shop_no_items": "Состав пуст — лот ничего не выдаст.",
    "admin_shop_item_line": "🆔{item_id} {type} {payload} ×{quantity}",
    "admin_shop_title": "🛒 Магазин",
    "admin_shop_empty": "Лотов пока нет.",
    "admin_shop_create_btn": "➕ Создать лот",
    "admin_shop_create_prompt": "Пришлите: название | цена | описание (описание необязательно). Фото — в подписи. Пример: VIP-набор | 500000 | Ускоренный старт",
    "admin_shop_created": "Лот создан: ID {lot_id}.",
    "admin_shop_edit_btn": "✏️ Изменить",
    "admin_shop_edit_prompt": "Пришлите строки поле=значение (title, description, price).",
    "admin_shop_add_item_btn": "➕ Добавить предмет",
    "admin_shop_add_item_prompt": "Введите: тип {payload_json} количество\nТипы: money, car, container, skill, vip, battle_pass, other.\nПример: money {\"amount\": 5000} 1",
    "admin_shop_item_invalid": "Не удалось разобрать предмет. Формат: тип {payload_json} количество.",
    "admin_shop_disable_btn": "🔴 Сделать недоступным",
    "admin_shop_enable_btn": "🟢 Сделать доступным",
    "admin_bp_none": "Активный Battle Pass не создан.",
    "admin_bp_no_levels": "Уровней пока нет.",
    "admin_bp_create_btn": "➕ Создать Battle Pass",
    "admin_bp_add_level_btn": "➕ Награда уровня",
    "admin_bp_create_prompt": "Пришлите: название | цена | уровней | дней. Пример: Сезон 1 | 200000 | 50 | 30",
    "admin_bp_add_reward_prompt": "Введите: номер_уровня тип {payload_json}\nПример: 5 money {\"amount\": 10000}",
    "admin_bp_reward_invalid": "Не удалось разобрать награду. Формат: номер_уровня тип {payload_json}.",
    "admin_vip_title": "👑 Настройки VIP",
    "admin_vip_price_line": "Цена: {price}",
    "admin_vip_bonus_line": "Бонус мест гаража: {bonus}",
    "admin_vip_edit_btn": "✏️ Изменить",
    "admin_vip_edit_prompt": "Пришлите строки вида ключ=значение:\nvip_price=500000\ngarage_vip_bonus_slots=10\ncommission_quick_sell=0.10,0.05\n(формат комиссии: regular,vip). Ключи комиссий: commission_quick_sell, commission_sell_state, commission_sell_player, commission_transfer.",
    "admin_promo_title": "🎟 Промокоды",
    "admin_promo_empty": "Промокодов пока нет.",
    "admin_promo_create_btn": "➕ Создать промокод",
    "admin_promo_create_prompt": "Пришлите: код | лимит_активаций_или_- | rewards_json\nПример: WELCOME | 100 | [{{\"type\": \"money\", \"amount\": 5000}}]",
    "admin_promo_code_taken": "Такой код уже существует.",
    "admin_promo_created": "Промокод создан: {code}.",
    "admin_promo_activations_line": "Активаций: {used}/{limit}",
    "admin_promo_expires_line": "Истекает: {expires}",
    "admin_promo_disabled_label": "🔴 Выключен",
    "admin_promo_disable_btn": "🔴 Выключить",
    "admin_promo_enable_btn": "🟢 Включить",
    "admin_groups_title": "👥 Группы",
    "admin_groups_empty": "Группы ещё не добавлены — отправьте /admin_addgroup в группе.",
    "admin_group_added": "Группа добавлена в управление.",
    "admin_group_auction_status_line": "Аукцион: {status}",
    "admin_group_status_on": "включён",
    "admin_group_status_off": "выключен",
    "admin_group_inactive_label": "🔴 Неактивна",
    "admin_group_disable_auction_btn": "🔴 Выключить аукцион",
    "admin_group_enable_auction_btn": "🟢 Включить аукцион",
    "admin_group_remove_btn": "🗑 Удалить из управления",
    "admin_group_removed": "Группа удалена из управления.",
    "admin_owner_only": "Это действие доступно только владельцу бота.",
    "admin_admins_title": "🛡 Администраторы",
    "admin_admins_empty": "Администраторов пока нет.",
    "admin_admins_add_btn": "➕ Назначить",
    "admin_admins_revoke_row": "🗑 Снять: {label}",
    "admin_admins_add_prompt": "Введите Telegram ID или username игрока, которого назначить администратором:",
    "admin_admins_added": "Администратор назначен со всеми правами.",
    "admin_docs_title": "📖 Документация",
    "admin_docs_empty": "Разделов документации пока нет.",
    "admin_docs_create_btn": "➕ Новый раздел",
    "admin_docs_edit_btn": "✏️ Изменить",
    "admin_docs_delete_btn": "🗑 Удалить",
    "admin_docs_key_prompt": "Введите ключ раздела (например: rules, containers, vip):",
    "admin_docs_content_prompt": "Пришлите одним сообщением:\nЗаголовок RU | Текст RU ||| Заголовок EN | Текст EN",
    "admin_docs_format_invalid": "Не удалось разобрать. Формат: Заголовок RU | Текст RU ||| Заголовок EN | Текст EN — все 4 части обязательны.",
    "admin_docs_saved": "Раздел «{section_key}» сохранён на обоих языках.",
    "admin_docs_deleted": "Раздел удалён.",
    "admin_db_title": "🗄 База данных",
    "admin_db_export_btn": "⬇️ Экспорт",
    "admin_db_import_btn": "⬆️ Импорт",
    "admin_db_export_done": "Экспорт готов.",
    "admin_db_import_prompt": "Пришлите JSON-файл экспорта.",
    "admin_db_import_need_file": "Нужен файл (документ), не текст.",
    "admin_db_import_invalid_file": "Не удалось прочитать файл — это должен быть JSON, созданный экспортом.",
    "admin_db_import_summary": "Машин: {cars} · Контейнеров: {containers} · Настроек: {settings} · Лотов: {lots} · Промокодов: {promos}",
    "admin_db_import_cancelled": "Импорт отменён.",
    "admin_db_import_done": "Импорт применён.",
    "admin_bc_create_btn": "➕ Создать рассылку",
    "admin_bc_stop_btn": "⏹ Остановить",
    "admin_bc_delete_btn": "🗑 Удалить",
    "admin_bc_title": "📣 Рассылки",
    "admin_bc_empty": "Рассылок пока нет.",
    "admin_bc_stats_line": "Отправлено: {sent} · Ошибок: {failed} · В очереди: {pending}",
    "admin_bc_content_prompt": "Пришлите контент рассылки: текст, фото, видео, документ, GIF, голосовое или стикер (подпись к медиа — тоже текст сообщения).",
    "admin_bc_content_invalid": "Такой тип контента не поддерживается для рассылки.",
    "admin_bc_buttons_prompt": "Добавить inline-кнопки? Пришлите JSON вида [[{\"text\": \"Открыть\", \"url\": \"https://...\"}]] или «-», если без кнопок.",
    "admin_bc_buttons_invalid": "Не удалось разобрать кнопки. Формат: [[{\"text\": ..., \"url\": ...}]] или «-».",
    "admin_bc_audience_prompt": "Выберите аудиторию:",
    "admin_bc_schedule_prompt": "Выберите расписание:",
    "admin_bc_created": "Рассылка создана: ID {broadcast_id}.",
    "admin_bc_aud_all": "Все",
    "admin_bc_aud_ru": "RU",
    "admin_bc_aud_en": "EN",
    "admin_bc_aud_vip": "VIP",
    "admin_bc_aud_regular": "Обычные",
    "admin_bc_aud_active": "Активные",
    "admin_bc_aud_inactive": "Неактивные",
    "admin_bc_sched_now": "🚀 Сразу",
    "admin_bc_sched_daily": "🔁 Ежедневно",
    "admin_bc_sched_weekly": "🔁 Еженедельно",
    "admin_import_confirm": "Подтвердите импорт базы данных — это перезапишет текущие данные.",

    # --- Admin: Statistics ---
    "admin_stats_period_day": "24 ч",
    "admin_stats_period_week": "7 дн",
    "admin_stats_period_month": "30 дн",
    "admin_stats_period_all": "Всё время",
    "admin_stats_text": "📊 Статистика · {period}\n\n👥 Игроков: {players}\n🟢 Активных: {active}\n🆕 Новых: {new}\n👑 VIP: {vip}\n🚫 Забанено: {banned}\n\n📦 Контейнеров: {containers}\n🔥 Ставок: {bets}\n🏆 Побед: {wins}\n🚗 Машин выдано: {cars}\n💰 Продано государству/быстро: {cars_sold}\n🤝 Продаж игрокам: {player_sales}\n\n🛒 Покупок: {purchases} ({purchases_sum})\n💵 Выдано денег: {issued}\n💸 Потрачено: {spent}\n🏦 Комиссии: {commissions}\n\n👥 Рефералов: {referrals}\n🎫 BP куплено: {bp}\n🎟 Промокодов активировано: {promo}\n⚠️ Ошибок: {errors}\n💬 Групп: {groups}\n📣 Рассылок отправлено: {broadcasts}",

    # --- History ---
    "admin_action_history": "📜 История",
    "admin_history_title": "📜 История {user}\nСтр. {page}/{pages} · всего {total}",
    "admin_history_empty": "Событий пока нет.",
    "hist_registered": "🆕 Регистрация",
    "hist_language_changed": "🌐 Смена языка",
    "hist_agreed_docs": "✅ Согласие с правилами",
    "hist_bet": "🔥 Ставка",
    "hist_container_won": "🏆 Выигран контейнер",
    "hist_car_obtained": "🚗 Получена машина",
    "hist_car_sold": "💰 Машина продана",
    "hist_car_given": "📤 Машина передана",
    "hist_car_received": "📥 Машина получена от игрока",
    "hist_promo_redeemed": "🎟 Промокод",
    "hist_referral_invited": "👥 Приглашён игрок",
    "hist_referral_joined": "👥 Пришёл по приглашению",
    "hist_shop_purchase": "🛒 Покупка в магазине",
    "hist_vip_granted": "👑 VIP получен",
    "hist_vip_revoked": "👑 VIP снят",
    "hist_bp_level_up": "🎫 Уровень BP",
    "hist_admin_balance": "🛡 Админ: баланс",
    "hist_admin_ban": "🛡 Админ: блокировка",
    "hist_admin_unban": "🛡 Админ: разблокировка",
    "hist_admin_vip_grant": "🛡 Админ: выдал VIP",
    "hist_admin_vip_revoke": "🛡 Админ: снял VIP",
    "hist_system_error": "⚠️ Ошибка",
    "hist_money_bet": "💵 Ставка (списание)",
    "hist_money_bet_refund": "💵 Возврат ставки",
    "hist_money_container_win_cost": "💵 Оплата выигранного контейнера",
    "hist_money_sell_state": "💵 Продажа государству",
    "hist_money_sell_player_income": "💵 Продажа игроку",
    "hist_money_buy_player_car": "💵 Покупка машины у игрока",
    "hist_money_quick_sell": "💵 Быстрый выкуп",
    "hist_money_transfer_out": "💵 Перевод отправлен",
    "hist_money_transfer_in": "💵 Перевод получен",
    "hist_money_daily_bonus": "💵 Ежедневный бонус",
    "hist_money_referral_bonus": "💵 Бонус за реферала",
    "hist_money_shop_purchase": "💵 Оплата магазина",
    "hist_money_promo_reward": "💵 Награда промокода",
    "hist_money_battle_pass_purchase": "💵 Покупка BP",
    "hist_money_battle_pass_reward": "💵 Награда BP",
    "hist_money_vip_purchase": "💵 Покупка VIP",
    "hist_money_garage_upgrade": "💵 Расширение гаража",
    "hist_money_admin_adjust": "💵 Изменение баланса админом",

    # --- Admin: Backups ---
    "admin_bkp_text": "💾 Резервные копии\n\nАвто: {state}\nВремя: {hour} UTC\nХранить копий: {keep}\nПоследняя: {last}\n\n{files}\n\nКопии получает только владелец.",
    "admin_bkp_state_on": "включено",
    "admin_bkp_state_off": "выключено",
    "admin_bkp_create_btn": "💾 Создать сейчас",
    "admin_bkp_on_btn": "▶️ Включить авто",
    "admin_bkp_off_btn": "⏸ Выключить авто",
    "admin_bkp_hour_btn": "🕒 Час",
    "admin_bkp_keep_btn": "🗂 Копий",
    "admin_bkp_started": "Создаю копию…",
    "admin_bkp_done": "Готово: {name}\nФайл отправлен владельцу.",
    "admin_bkp_failed": "Не удалось создать копию. Подробности в логах.",
    "admin_bkp_unsent": "⚠️ Не отправлено владельцу: {name}. Повторю автоматически.",

    # --- Container inventory ---
    "garage_containers_btn": "📦 Контейнеры",
    "container_inv_title": "📦 Ваши контейнеры:",
    "container_inv_empty": "Контейнеров нет.",
    "container_inv_open_btn": "Открыть {name} ×{qty}",
    "container_inv_none": "Этого контейнера нет.",
    "container_inv_opened": "📦 Контейнер открыт!",
    "container_inv_auto_sold": "Гараж полон — машина продана за ${amount}.",
    "hist_container_received": "📦 Получен контейнер",
    "hist_container_removed": "📦 Контейнер изъят",
    "hist_container_opened": "📦 Открыт контейнер",
    "hist_admin_car_give": "🛡 Админ: выдал машину",
    "hist_admin_car_take": "🛡 Админ: забрал машину",
    "hist_admin_container_give": "🛡 Админ: выдал контейнер",
    "hist_admin_container_take": "🛡 Админ: забрал контейнер",
    "hist_admin_bp_give": "🛡 Админ: выдал BP",
    "hist_admin_skill_give": "🛡 Админ: выдал навык",
    "hist_admin_garage_capacity": "🛡 Админ: вместимость гаража",

    # --- Admin items / Skills ---
    "admin_section_skills": "⬆️ Навыки",
    "admin_item_car_give_btn": "🚗 Выдать машину",
    "admin_item_car_take_btn": "🚗 Забрать машину",
    "admin_item_container_give_btn": "📦 Выдать контейнер",
    "admin_item_container_take_btn": "📦 Забрать контейнер",
    "admin_item_bp_give_btn": "🎫 Выдать BP",
    "admin_item_skill_give_btn": "⬆️ Выдать навык",
    "admin_item_garage_set_btn": "🏠 Вместимость гаража",
    "admin_item_car_give_prompt": "Введите ID машины из каталога.",
    "admin_item_car_take_prompt": "Введите ID машины игрока (как в его гараже).",
    "admin_item_container_give_prompt": "Введите: ID_контейнера [количество]",
    "admin_item_container_take_prompt": "Введите: ID_контейнера [количество]",
    "admin_item_skill_give_prompt": "Введите: ID_навыка [уровень]",
    "admin_item_garage_set_prompt": "Введите новую вместимость гаража (число).",
    "admin_item_done": "✅ Готово.",
    "admin_item_invalid": "Неверные данные.",
    "admin_item_not_enough": "У игрока нет столько контейнеров.",
    "admin_item_no_bp": "Активного BP нет.",
    "admin_item_bp_already": "BP уже куплен.",
    "admin_skills_title": "⬆️ Навыки:",
    "admin_skills_empty": "Навыков нет.",
    "admin_skill_create_btn": "➕ Создать навык",
    "admin_skill_delete_btn": "🗑 Удалить",
    "admin_skill_create_prompt": "Введите: Название | Описание | макс. уровень\nПример: Торговец | Выгоднее продажи | 5",
    "admin_skill_create_invalid": "Формат: Название | Описание | макс. уровень (число ≥ 1).",
    "admin_skill_created": "✅ Навык #{id} «{name}» создан.",
    "admin_skill_card": "⬆️ Навык #{id}\n{name}\n{description}\nМакс. уровень: {max_level}",
    "skills_title": "⬆️ Ваши навыки:",
    "skills_empty": "Навыков пока нет. Их дают BP, магазин и промокоды.",
    "skills_line": "• {name} — {level}/{max_level}",
}
